Small update to patch
../lib/dns/rdataslab.c
../lib/dns/rdataslab.c:168:3: error: expression result unused; should this cast be to 'void'? [-Werror,-Wunused-value]
  168 |                 (void *)newslab(rdataset, mctx, region, 0, buflen);
      |